// <auto-generated />
using System;
using MealPlanner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260405124952_AddFoodCategory")]
    partial class AddFoodCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("ActiveMacroId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_macro_id");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("meals_per_day");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("ActiveMacroId")
                        .HasDatabaseName("idx_configuration_active_macro");

                    b.ToTable("configuration", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Export", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid?>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_export_user_id");

                    b.ToTable("export", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CarbsPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_per_100");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("FatPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_per_100");

                    b.Property<Guid?>("IconId")
                        .HasColumnType("uuid")
                        .HasColumnName("icon_id");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom");

                    b.Property<decimal>("KcalPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("kcal_per_100");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("Per100UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("per_100_unit_id");

                    b.Property<decimal>("ProteinPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_per_100");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .HasDatabaseName("idx_food_icon_id");

                    b.HasIndex("Per100UnitId")
                        .HasDatabaseName("idx_food_per_100_unit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_food_user_id");

                    b.ToTable("food", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Icon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("icon", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Macro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CarbsG")
                        .HasColumnType("integer")
                        .HasColumnName("carbs_g");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FatG")
                        .HasColumnType("integer")
                        .HasColumnName("fat_g");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<int>("ProteinG")
                        .HasColumnType("integer")
                        .HasColumnName("protein_g");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_macro_user_id");

                    b.ToTable("macro", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MacroLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CarbsG")
                        .HasColumnType("integer")
                        .HasColumnName("carbs_g");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<int>("FatG")
                        .HasColumnType("integer")
                        .HasColumnName("fat_g");

                    b.Property<Guid?>("MacroId")
                        .HasColumnType("uuid")
                        .HasColumnName("macro_id");

                    b.Property<int>("ProteinG")
                        .HasColumnType("integer")
                        .HasColumnName("protein_g");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MacroId")
                        .HasDatabaseName("idx_macro_log_macro_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_macro_log_user_id");

                    b.ToTable("macro_log", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayNo")
                        .HasColumnType("integer")
                        .HasColumnName("day_no");

                    b.Property<int>("MealNo")
                        .HasColumnType("integer")
                        .HasColumnName("meal_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("idx_meal_plan_id");

                    b.ToTable("meal", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CarbsPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_per_100");

                    b.Property<decimal>("FatPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_per_100");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<decimal>("KcalPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("kcal_per_100");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<Guid>("Per100UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("per_100_unit_id");

                    b.Property<decimal>("ProteinPer100")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_per_100");

                    b.Property<Guid>("QuantityUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_id");

                    b.Property<decimal>("QuantityValue")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_value");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("idx_meal_item_food_id");

                    b.HasIndex("MealId")
                        .HasDatabaseName("idx_meal_item_meal_id");

                    b.HasIndex("Per100UnitId")
                        .HasDatabaseName("idx_meal_item_per_100_unit_id");

                    b.HasIndex("QuantityUnitId")
                        .HasDatabaseName("idx_meal_item_quantity_unit_id");

                    b.ToTable("meal_item", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<Guid?>("MacroId")
                        .HasColumnType("uuid")
                        .HasColumnName("macro_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MacroId")
                        .HasDatabaseName("idx_plan_macro_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_plan_user_id");

                    b.ToTable("plan", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.ShopItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<Guid>("QuantityUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_id");

                    b.Property<decimal>("TotalQuantityValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_quantity_value");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("idx_shop_item_food_id");

                    b.HasIndex("ListId")
                        .HasDatabaseName("idx_shop_item_list_id");

                    b.HasIndex("QuantityUnitId")
                        .HasDatabaseName("idx_shop_item_quantity_unit_id");

                    b.ToTable("shop_item", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.ShopList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("idx_shop_list_plan_id");

                    b.ToTable("shop_list", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Configuration", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Macro", "ActiveMacro")
                        .WithMany()
                        .HasForeignKey("ActiveMacroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithOne("Configuration")
                        .HasForeignKey("MealPlanner.Domain.Entities.Configuration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveMacro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Export", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.ShopList", "List")
                        .WithMany("Exports")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.Plan", "Plan")
                        .WithMany("Exports")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithMany("Exports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Food", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Icon", "Icon")
                        .WithMany("Foods")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.Unit", "Per100Unit")
                        .WithMany("FoodsPer100Unit")
                        .HasForeignKey("Per100UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithMany("Foods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Per100Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Macro", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithMany("Macros")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MacroLog", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Macro", "Macro")
                        .WithMany()
                        .HasForeignKey("MacroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithMany("MacroLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Meal", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Plan", "Plan")
                        .WithMany("Meals")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Food", "Food")
                        .WithMany("MealItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Unit", "Per100Unit")
                        .WithMany("MealItemsPer100Unit")
                        .HasForeignKey("Per100UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Unit", "QuantityUnit")
                        .WithMany("MealItemsQuantityUnit")
                        .HasForeignKey("QuantityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("Per100Unit");

                    b.Navigation("QuantityUnit");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Plan", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Macro", "Macro")
                        .WithMany("Plans")
                        .HasForeignKey("MacroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Profile", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MealPlanner.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.ShopItem", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Food", "Food")
                        .WithMany("ShopItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.ShopList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Unit", "QuantityUnit")
                        .WithMany("ShopItemsQuantityUnit")
                        .HasForeignKey("QuantityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("List");

                    b.Navigation("QuantityUnit");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.ShopList", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Plan", "Plan")
                        .WithMany("ShopLists")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Food", b =>
                {
                    b.Navigation("MealItems");

                    b.Navigation("ShopItems");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Icon", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Macro", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Exports");

                    b.Navigation("Meals");

                    b.Navigation("ShopLists");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.ShopList", b =>
                {
                    b.Navigation("Exports");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Unit", b =>
                {
                    b.Navigation("FoodsPer100Unit");

                    b.Navigation("MealItemsPer100Unit");

                    b.Navigation("MealItemsQuantityUnit");

                    b.Navigation("ShopItemsQuantityUnit");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Exports");

                    b.Navigation("Foods");

                    b.Navigation("MacroLogs");

                    b.Navigation("Macros");

                    b.Navigation("Plans");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
